version: '3.7'
services:
  grafana:
    container_name: yesoreyeram-infinity-datasource
    image: grafana/grafana-enterprise:${GF_VERSION:-main}
    # image: grafana/grafana-enterprise:${GF_VERSION:-latest}
    # image: grafana/grafana-enterprise:${GF_VERSION:-9.4.3}
    # image: grafana/grafana-enterprise:${GF_VERSION:-8.4.7}
    ports:
      - '3000:3000'
    volumes:
      - ./provisioning/dashboards-actual/:/dashboards/
      - ./provisioning:/etc/grafana/provisioning
      - ./dist/:/var/lib/grafana/plugins/yesoreyeram-infinity-datasource
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=infinity
      - GF_SECURITY_ADMIN_PASSWORD=infinity
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
      - GF_SECURITY_CSRF_ALWAYS_CHECK=true
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
      # - GF_FEATURE_TOGGLES_ENABLE=trimDefaults disableEnvelopeEncryption database_metrics live-service-web-workerqueryOverLive panelTitleSearch prometheusAzureOverrideAudience publicDashboards publicDashboardsEmailSharing lokiLive featureHighlights migrationLocking storage exploreMixedDatasource newTraceViewHeader correlations cloudWatchDynamicLabels datasourceQueryMultiStatus traceToMetrics newDBLibrary validateDashboardsOnSave autoMigrateOldPanels disableAngular prometheusWideSeries canvasPanelNesting scenes disableSecretsCompatibility logRequestsInstrumentedAsUnknown dataConnectionsConsole internationalization topnav grpcServer entityStore cloudWatchCrossAccountQuerying redshiftAsyncQueryDataSupport athenaAsyncQueryDataSupport newPanelChromeUI showDashboardValidationWarnings mysqlAnsiQuotes accessControlOnCall nestedFolders accessTokenExpirationCheck showTraceId datasourceOnboarding emptyDashboardPage authnService disablePrometheusExemplarSampling alertingBacktesting editPanelCSVDragAndDrop alertingNoNormalState logsSampleInExplore logsContextDatasourceUi lokiQuerySplitting lokiQuerySplittingConfig individualCookiePreferences onlyExternalOrgRoleSync traceqlSearch prometheusMetricEncyclopedia timeSeriesTable prometheusResourceBrowserCache influxdbBackendMigration clientTokenRotation prometheusDataplane lokiMetricDataplane dataplaneFrontendFallback disableSSEDataplane alertStateHistoryLokiSecondary alertStateHistoryLokiPrimary alertStateHistoryLokiOnly unifiedRequestLog renderAuthJWT pyroscopeFlameGraph externalServiceAuth useCachingService enableElasticsearchBackendQuerying authenticationConfigUI pluginsAPIManifestKey advancedDataSourcePicker opensearchDetectVersion enableDatagridEditing
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards topnav dataConnectionsConsole newPanelChromeUI emptyDashboardPage correlations nestedFolders advancedDataSourcePicker
      - GF_PLUGIN_YESOREYERAM_INFINITY_DATASOURCE_TRACING=true
      - GF_INSTANCE_OTLP_ADDRESS=${GF_INSTANCE_OTLP_ADDRESS:-foo}
      - GF_INSTANCE_OTLP_PROPAGATION=${GF_INSTANCE_OTLP_PROPAGATION:-w3c}
